### ISSUE TITLE
Failed to compile in Linux for WiiU

### ISSUE THREAD

**Issue by bugalo** [aboood40091/sm64-port#25] opened 2022-05-15 18:50 UTC
When trying to compile the Wii U version in Linux, I get the following errors:

Compiling: src/pc/gfx/gfx_gx2_window.cpp -> build/us_wiiu/src/pc/gfx/gfx_gx2_window.o
src/pc/gfx/gfx_gx2_window.cpp: In function 'void gfx_gx2_window_exit_callback()':
src/pc/gfx/gfx_gx2_window.cpp:80:5: error: 'KPADShutdown' was not declared in this scope; did you mean 'WPADShutdown'?
   80 |     KPADShutdown();
      |     ^~~~~~~~~~~~
      |     WPADShutdown
src/pc/gfx/gfx_gx2_window.cpp: In function 'bool gfx_gx2_window_foreground_acquire_callback()':
src/pc/gfx/gfx_gx2_window.cpp:283:58: error: invalid conversion from 'int' to 'GX2SurfaceUse' [-fpermissive]
  283 |     g_depth_buffer.surface.use = GX2_SURFACE_USE_TEXTURE | GX2_SURFACE_USE_DEPTH_BUFFER;
      |                                  ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                          |
      |                                                          int
make: *** [Makefile:906: build/us_wiiu/src/pc/gfx/gfx_gx2_window.o] Error 1

I see that the file src/pc/gfx/gfx_gx2_window.cpp was updated 2 days ago, so I guess a recent change breaks it. I was able to compile the code some time ago.

Thanks!

**Comment by GABO1423** [comment] 2022-05-15 23:40
Duplicate of #24. Update wut and the issue should be fixed.

**Comment by bugalo** [comment] 2022-05-16 08:19
Thanks for your reply.

I have updated to the latest wut release. Running pacman -Qi wut provides:

Name            : wut
Version         : 1.0.0_beta12-1

Now I only have one of the errors:

Compiling: src/pc/gfx/gfx_gx2_window.cpp -> build/us_wiiu/src/pc/gfx/gfx_gx2_window.o
src/pc/gfx/gfx_gx2_window.cpp: In function 'void gfx_gx2_window_exit_callback()':
src/pc/gfx/gfx_gx2_window.cpp:80:5: error: 'KPADShutdown' was not declared in this scope; did you mean 'WPADShutdown'?
   80 |     KPADShutdown();
      |     ^~~~~~~~~~~~
      |     WPADShutdown
make: *** [Makefile:906: build/us_wiiu/src/pc/gfx/gfx_gx2_window.o] Error 1


Should the wut stable release from pacman work, or should I compile it form the repository?

**Comment by GABO1423** [comment] 2022-05-16 11:50
Yeah, the pacman package isn't up to date yet sadly. So you need to compile wut from source and update it manually

**Comment by GABO1423** [comment] 2022-05-16 21:05
> I can confirm that compiling wut from source fixes the issue. You can mark the issue as solved.
> 
> Thanks!

Glad to hear its working now!.... But you can close the issue yourself as well too.

Anyways, glad to have helped.

**Closed** 2022-05-17 02:00 UTC
